In [2]:
import yfinance as yahooFinance
import pandas as pd


list = ["AAPL", "ABT"]
pd.DataFrame(yahooFinance.download(list, start="2022-01-02")["Adj Close"])

[*********************100%%**********************]  2 of 2 completed

                  AAPL         ABT
Date
2022-01-03  179.953873  134.063431
2022-01-04  177.669998  130.910492
2022-01-05  172.943985  130.322327
2022-01-06  170.056976  130.303024
2022-01-07  170.225052  130.707993
...                ...         ...
2024-01-04  181.910004  110.980003
2024-01-05  181.179993  110.800003
2024-01-08  185.559998  112.400002
2024-01-09  185.139999  112.730003
2024-01-10  186.190002  114.400002

[508 rows x 2 columns]